# Generated by Django 5.0.6 on 2024-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendingMail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='to_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
